# Generated by Django 5.2.8 on 2025-12-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=255)),
                ('role', models.CharField(help_text="Job title or role (e.g., 'Managing Director', 'Operations Manager')", max_length=255)),
                ('description', models.TextField(help_text='Brief description or bio of the team member')),
                ('image', models.ImageField(blank=True, help_text='Profile photo of the team member', null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team member should be displayed on the Our People page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
