# Generated by Django 5.2.8 on 2025-12-07 08:49

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_add_content_index"),
    ]

    operations = [
        TrigramExtension(),
    ]
