# Generated by Django 5.2.8 on 2025-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theming", "0003_theme_scrolling_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="If set, this theme will be used globally as default (unless an event overrides it)",
            ),
        ),
    ]
