# Generated by Django 5.2.8 on 2025-12-14 21:24

from django.db import migrations


def add_themes(apps, schema_editor):
    Theme = apps.get_model("theming", "Theme")
    themes_data = [
        {
            "key": "new_year",
            "name": "New Year",
            "scrolling_message": "🎉 Happy New Year! Start the year with our premium fleet. 🎇",
            "scrolling_background_color": "#FFD700",
            "is_custom": False,
        },
        {
            "key": "valentines",
            "name": "Valentine's Day",
            "scrolling_message": "❤️ Celebrate Love with a Luxury Ride! Book Now. 🌹",
            "scrolling_background_color": "#FF69B4",
            "is_custom": False,
        },
        {
            "key": "summer_vibes",
            "name": "Summer Vibes",
            "scrolling_message": "☀️ Summer Sale! Get 10% off on convertibles this season. 🌴",
            "scrolling_background_color": "#FFA500",
            "is_custom": False,
        },
        {
            "key": "black_friday",
            "name": "Black Friday",
            "scrolling_message": "🖤 Black Friday Deals! Huge discounts on all luxury cars. 🛍️",
            "scrolling_background_color": "#000000",
            "is_custom": False,
        },
        {
            "key": "christmas",
            "name": "Christmas",
            "scrolling_message": "🎄 Merry Christmas! Travel in style this holiday season. ❄️",
            "scrolling_background_color": "#FF0000",
            "is_custom": False,
        },
    ]

    for data in themes_data:
        Theme.objects.update_or_create(key=data["key"], defaults=data)


def remove_themes(apps, schema_editor):
    Theme = apps.get_model("theming", "Theme")
    Theme.objects.filter(
        key__in=["new_year", "valentines", "summer_vibes", "black_friday", "christmas"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("theming", "0005_remove_theme_accent_color_remove_theme_animations_and_more"),
    ]

    operations = [
        migrations.RunPython(add_themes, remove_themes),
    ]
